### ISSUE TITLE
Doesn't support UEFI

### ISSUE THREAD

**Issue by cole-h** [DeterminateSystems/nix-netboot-serve#2]
When trying to boot a VM over iPXE utilizing OVMF (QEMU EFI software), the following error can be observed:

```
>>Start PXE over IPv4.
  Station IP address is 10.0.2.26

  Server IP address is 10.0.2.1
  NBP filename is http://10.0.2.1:3030/dispatch/configuration/small
  NBP filesize is 0 Bytes
  PXE-E99: Unexpected network error.
BdsDxe: failed to load Boot0005 "UEFI PXEv4 (MAC:000000000000)" from PciRoot(0x0)/Pci(0x3,0x0)/MAC(000000000000,0x1)/IPv4(0.0.0.0,0x0,DHCP,0.0.0.0,0.0.0.0,0.0.0.0): Not Found
```

After reading https://ipxe.org/appnote/uefihttp, it appears that iPXE expects an EFI file to be served, while this is serving the standard ipxe file.

**Comment by grahamc** [comment]
Solved in ipxe-boot-lab.

**Comment by cole-h** [comment]
Specifically, solved by https://github.com/DeterminateSystems/ipxe-boot-lab/pull/19.

**Comment by jkachmar** [comment]
any chance of this work being open sourced? i'm interested in running a few netboot experiments in an environment where UEFI would be preferred, if possible :)

**Comment by cole-h** [comment]
That repo should be public now :)
